---
- name: Add HAProxy PPA
  apt_repository:
    repo: ppa:vbernat/haproxy-2.9
    state: present

- name: Install HAProxy
  apt:
    name: haproxy
    update_cache: yes

- name: Template HAProxy configuration
  template:
    src: haproxy.cfg.j2
    dest: /etc/haproxy/haproxy.cfg
    validate: haproxy -c -f %s
  notify: restart haproxy
