---
- name: Remove existing repository configurations
  file:
    path: "{{ item }}"
    state: absent
  loop:
    - /etc/apt/sources.list
    - /etc/apt/sources.list.d

- name: Create sources.list.d directory
  file:
    path: /etc/apt/sources.list.d
    state: directory
    mode: '0755'

- name: Configure Ubuntu 22.04 repositories
  copy:
    content: |
      deb http://mirrors.digitalocean.com/ubuntu/ jammy main restricted universe multiverse
      deb http://mirrors.digitalocean.com/ubuntu/ jammy-updates main restricted universe multiverse
      deb http://mirrors.digitalocean.com/ubuntu/ jammy-backports main restricted universe multiverse
      deb http://security.ubuntu.com/ubuntu/ jammy-security main restricted universe multiverse
    dest: /etc/apt/sources.list
  when: ansible_distribution_version == "22.04"

- name: Configure Ubuntu 24.04 repositories
  copy:
    content: |
      deb http://mirrors.digitalocean.com/ubuntu/ noble main restricted universe multiverse
      deb http://mirrors.digitalocean.com/ubuntu/ noble-updates main restricted universe multiverse
      deb http://mirrors.digitalocean.com/ubuntu/ noble-backports main restricted universe multiverse
      deb http://security.ubuntu.com/ubuntu/ noble-security main restricted universe multiverse
    dest: /etc/apt/sources.list
  when: ansible_distribution_version == "24.04"

- name: Update apt cache
  apt:
    update_cache: yes

- name: Upgrade all packages
  apt:
    upgrade: dist
    force_apt_get: yes
  environment:
    UCF_FORCE_CONFFOLD: "1"

- name: Install basic packages
  apt:
    name:
      - sudo
      - neovim
      - neofetch
      - git
      - curl
      - wget
      - tmux
      - htop
      - foot-terminfo
      - kitty-terminfo
      - build-essential
      - rsync
      - aria2
      - snapd
    state: present

- name: Install Speedtest via snap
  snap:
    name: speedtest

- name: Setup Neovim config directory
  file:
    path: /root/.config/nvim
    state: directory
    mode: '0755'

- name: Configure Neovim
  copy:
    content: "set tabstop=4 softtabstop=0 expandtab shiftwidth=4 smarttab"
    dest: /root/.config/nvim/init.vim
    mode: '0644'
