---
all_domains: >-
  {%- set domains_list = [] -%}
  {%- macro extract_domains(item) -%}
    {%- if item is string -%}
      {{ domains_list.append(item) }}
    {%- elif item is mapping -%}
      {%- for val in item.values() -%}
        {{ extract_domains(val) }}
      {%- endfor -%}
    {%- elif item is iterable -%}
      {%- for val in item -%}
        {{ extract_domains(val) }}
      {%- endfor -%}
    {%- endif -%}
  {%- endmacro -%}
  {{ extract_domains(domains) }}
  {{ domains_list }}
