---
- name: Configure VPS
  hosts: vps
  become: true
  gather_facts: true

  pre_tasks:
    - name: Check OS version
      debug:
        msg: "Running on Debian {{ ansible_distribution_version }}"
      when: ansible_distribution == "Debian" and ansible_distribution_version | float >= 12.0

    - name: Verify Debian 12 or higher
      fail:
        msg: "This playbook requires Debian 12 (Bookworm) or higher"
      when: >
        ansible_distribution != "Debian" or 
        ansible_distribution_version | float < 12.0

  roles:
    - base_system
    - wireguard
    - certbot
    - haproxy
    - nginx
    - ocserv
    - certbot_renewal_config
    - network
    - fail2ban

  # post_tasks:
  #   - name: Reboot server
  #     reboot:
  #       msg: "Rebooting after setup"
  #       connect_timeout: 5
  #       reboot_timeout: 300
  #       pre_reboot_delay: 0
  #       post_reboot_delay: 30
