---
# DEPRECATED: Use site-moscow.yml or site-europe.yml instead
#
# This playbook is kept for reference but the infrastructure now uses
# separate playbooks for each VPS:
#   - site-moscow.yml: Moscow VPS (okhsunrog.ru) - VPN services, reverse proxy
#   - site-europe.yml: Europe VPS (okhsunrog.dev) - Blog, VPN exit node
#
# To deploy:
#   ansible-playbook site-moscow.yml
#   ansible-playbook site-europe.yml

- name: Legacy playbook - use site-moscow.yml or site-europe.yml
  hosts: localhost
  gather_facts: false
  tasks:
    - name: Show deprecation notice
      debug:
        msg: |
          This playbook is deprecated. Please use:
            - site-moscow.yml for Moscow VPS
            - site-europe.yml for Europe VPS

    - name: Fail with instructions
      fail:
        msg: "Use site-moscow.yml or site-europe.yml instead"
