---
- name: Configure VPS
  hosts: vps
  become: true
  gather_facts: true

  pre_tasks:
    - name: Check OS version
      debug:
        msg: "Running on Ubuntu {{ ansible_facts['distribution_version'] }}"
      when: ansible_facts['distribution'] == "Ubuntu" and ansible_facts['distribution_version'] in ['22.04', '24.04']

    - name: Verify Ubuntu 22.04 or higher
      fail:
        msg: "This playbook requires Ubuntu 22.04 (Jammy) or higher"
      when: >
        ansible_facts['distribution'] != "Ubuntu" or
        ansible_facts['distribution_version'] not in ['22.04', '24.04']

  roles:
    - base_system
    - wireguard
    - amneziawg
    - certbot
    - haproxy
    - nginx
    - ocserv
    - coturn
    - certbot_renewal_config
    - network
    - fail2ban

  post_tasks:
    - name: Reboot server
      reboot:
        msg: "Rebooting after setup"
        connect_timeout: 5
        reboot_timeout: 300
        pre_reboot_delay: 0
        post_reboot_delay: 30
