---
- name: Configure VPS
  hosts: vps
  become: true
  gather_facts: true

  pre_tasks:
    - name: Check OS version
      debug:
        msg: "Running on Debian {{ ansible_distribution_version }}"
      when: ansible_distribution == "Debian" and ansible_distribution_version | float >= 12.0

    - name: Verify Debian 12 or higher
      fail:
        msg: "This playbook requires Debian 12 (Bookworm) or higher"
      when: >
        ansible_distribution != "Debian" or 
        ansible_distribution_version | float < 12.0

  roles:
    - base_system
    - wireguard
    - certbot
    - haproxy
    - nginx
    - ocserv
    - network
