---
- name: Check if ocserv is installed
  command: which ocserv
  register: ocserv_check
  ignore_errors: true
  changed_when: false

- name: Include installation tasks if ocserv is not installed
  include_tasks: install.yml
  when: ocserv_check.rc != 0

- name: Setup ocserv instances
  include_tasks: setup_instance.yml
  loop: "{{ ocserv_instances }}"
  loop_control:
    loop_var: instance
    label: "{{ instance.instance_id }}"

- name: Register deployed ocserv services
  set_fact:
    ocserv_deployed_services: "{{ ocserv_deployed_services | default([]) + ['ocserv-' + instance.instance_id + '.service'] }}"
  loop: "{{ ocserv_instances }}"
  loop_control:
    loop_var: instance
